
name: solve daily worlde (macOS)

on:
  push:
    branches:
      - main
  #schedule:
   # - cron: "40 1 * * *"
  #workflow_dispatch:
  #  branches:

jobs:
  build:

    env:
      PY_COLORS: "1"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel
        pip install -r requirements.txt
    - name: Install SeleniumBase
      run: |
        pip install seleniumbase
    - name: Check the console scripts interface
      run: |
        seleniumbase
        sbase
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py
    - name: Make sure nosetests is working
      run: |
        echo "def test_2(): pass" > nothing2.py
        nosetests nothing2.py
    - name: pytest wordle.py
      run: |
        pytest wordle.py
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "maksbertonclej@gmail.com"
        git config --local user.name "mihaMaks"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  
